/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as IskiDanismanlikRouteImport } from './routes/iski-danismanlik'
import { Route as ProjeHizmetleriRouteImport } from './routes/proje-hizmetleri'
import { Route as SayacAyrimiRouteImport } from './routes/sayac-ayrimi'
import { Route as SuKacagiTespitRouteImport } from './routes/su-kacagi-tespit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const IskiDanismanlikRoute = IskiDanismanlikRouteImport.update({
  id: '/iski-danismanlik',
  path: '/iski-danismanlik',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjeHizmetleriRoute = ProjeHizmetleriRouteImport.update({
  id: '/proje-hizmetleri',
  path: '/proje-hizmetleri',
  getParentRoute: () => rootRouteImport,
} as any)
const SayacAyrimiRoute = SayacAyrimiRouteImport.update({
  id: '/sayac-ayrimi',
  path: '/sayac-ayrimi',
  getParentRoute: () => rootRouteImport,
} as any)
const SuKacagiTespitRoute = SuKacagiTespitRouteImport.update({
  id: '/su-kacagi-tespit',
  path: '/su-kacagi-tespit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iski-danismanlik': typeof IskiDanismanlikRoute
  '/proje-hizmetleri': typeof ProjeHizmetleriRoute
  '/sayac-ayrimi': typeof SayacAyrimiRoute
  '/su-kacagi-tespit': typeof SuKacagiTespitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iski-danismanlik': typeof IskiDanismanlikRoute
  '/proje-hizmetleri': typeof ProjeHizmetleriRoute
  '/sayac-ayrimi': typeof SayacAyrimiRoute
  '/su-kacagi-tespit': typeof SuKacagiTespitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iski-danismanlik': typeof IskiDanismanlikRoute
  '/proje-hizmetleri': typeof ProjeHizmetleriRoute
  '/sayac-ayrimi': typeof SayacAyrimiRoute
  '/su-kacagi-tespit': typeof SuKacagiTespitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iski-danismanlik'
    | '/proje-hizmetleri'
    | '/sayac-ayrimi'
    | '/su-kacagi-tespit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iski-danismanlik'
    | '/proje-hizmetleri'
    | '/sayac-ayrimi'
    | '/su-kacagi-tespit'
  id:
    | '__root__'
    | '/'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iski-danismanlik'
    | '/proje-hizmetleri'
    | '/sayac-ayrimi'
    | '/su-kacagi-tespit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HizmetlerRoute: typeof HizmetlerRoute
  IskiDanismanlikRoute: typeof IskiDanismanlikRoute
  ProjeHizmetleriRoute: typeof ProjeHizmetleriRoute
  SayacAyrimiRoute: typeof SayacAyrimiRoute
  SuKacagiTespitRoute: typeof SuKacagiTespitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iski-danismanlik': {
      id: '/iski-danismanlik'
      path: '/iski-danismanlik'
      fullPath: '/iski-danismanlik'
      preLoaderRoute: typeof IskiDanismanlikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proje-hizmetleri': {
      id: '/proje-hizmetleri'
      path: '/proje-hizmetleri'
      fullPath: '/proje-hizmetleri'
      preLoaderRoute: typeof ProjeHizmetleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sayac-ayrimi': {
      id: '/sayac-ayrimi'
      path: '/sayac-ayrimi'
      fullPath: '/sayac-ayrimi'
      preLoaderRoute: typeof SayacAyrimiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/su-kacagi-tespit': {
      id: '/su-kacagi-tespit'
      path: '/su-kacagi-tespit'
      fullPath: '/su-kacagi-tespit'
      preLoaderRoute: typeof SuKacagiTespitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HizmetlerRoute: HizmetlerRoute,
  IskiDanismanlikRoute: IskiDanismanlikRoute,
  ProjeHizmetleriRoute: ProjeHizmetleriRoute,
  SayacAyrimiRoute: SayacAyrimiRoute,
  SuKacagiTespitRoute: SuKacagiTespitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
